apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::202434812648:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::202434812648:role/eksctl-eksctl-demo-nodegroup-ng-3-NodeInstanceRole-AEC4XIYW4X4V
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-28T10:40:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1562"
  uid: bbab5aa5-20ea-4209-8bc3-e2d7953b66f9
